"""add image column to products table

Revision ID: 70659dadfd3d
Revises: 5c55304c6cbd
Create Date: 2025-06-18 13:40:25.860286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70659dadfd3d'
down_revision = '5c55304c6cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
